### ISSUE TITLE
Add support for SetEscapeHTML()

### ISSUE THREAD

**Issue by csystem-it** [spyzhov/ajson#53]
Hi,

It seems that ajson, by default, when marshal value escape certain character as Unicode escapes.
The standard library provide the function SetEscapeHTML to override this behaviour, it would be useful if ajson implemented the same function or something equivalent.

It seems that the internal quoteString() function already has this functionality implemented, but is not exposed in the public api.

Thank you,

**Comment by spyzhov** [comment]
Hello,

Good point! Thanks, I will add this functionality soon :+1:

**Comment by spyzhov** [comment]
Hello,

First of all, I'd like to thank you for the request. I thought a lot about it, trying to find a solution that could cover all use cases.

I apologize for the initially encouraging answer, but I have to reject this feature request, no matter how much it fits the standard library. The main problem - it can't be done idempotent with no costs.

Hidden strength of this library is the cheap encoding. If some node of the object was decoded from the source and wasn't modified before the encoding process, it will be transferred to the encoded part "as-is", from the source, instead of encoding the value itself.

If I want to add `SetEscapeHTML` method, I have to add it to the encoder and decoder parts, and I have always to encode the value of string-typed nodes, instead of transferring it "as-is".

I will think of adding it in the next version of the library, as I will probably change the way of storing data.

In the current version of the library, please use the method `html.EscapeString` from the library ["html"](https://pkg.go.dev/html#EscapeString).

I prepared 2 examples of how you can do it: 

Example row ([playground](https://play.golang.com/p/C7NUXIqt4_p))
```golang
	nodes, _ := root.JSONPath("$..*")
	for _, node := range nodes {
		if node.IsString() {
			_ = node.SetString(html.EscapeString(node.MustString()))
		}
	}
```

Example with function ([playground](https://play.golang.com/p/FSWpEw2fzmm))
```golang
	ajson.AddFunction("is_string", func(node *ajson.Node) (result *ajson.Node, err error) {
		return ajson.BoolNode("", node.IsString()), nil
	})

	nodes, _ := root.JSONPath("$..[?(is_string(@))]")
	for _, node := range nodes {
		_ = node.SetString(html.EscapeString(node.MustString()))
	}
```

The main difference is when to test the type of node.
